// Original, house-written gambling aphorisms (not quoted from any source).
// Shown at random in the side panels, with a rotating neon colour.
export const QUOTES: string[] = [
  "The house always sleeps well.",
  "Every chip remembers the hand that dropped it.",
  "Fortune is loud; ruin is louder.",
  "Bet the line you can lose, not the line you can't.",
  "Luck is rented, never owned.",
  "The cooler is always one tap away.",
  "Greed buys the ticket; fear forgets to cash it.",
  "Stop is a verb. Use it.",
  "A streak is a story you tell after it ends.",
  "The grid doesn't care how you feel.",
  "Win small, leave big.",
  "Tilt is a tax on memory.",
  "No candle owes you a close.",
  "The skull was always there. You just hadn't found it.",
  "Cash out is the only sure multiplier.",
  "Risk is a price; courage is just paying it.",
  "Edge eats patience for breakfast.",
  "The market is a mirror with a grudge.",
  "Quit while the neon's still flattering you.",
  "Every gambler is a temporary genius.",
  "Variance is loud near the exit.",
  "The next tap is never the last tap.",
  "Hope is not a position.",
  "Big numbers glow brightest right before zero.",
  "Discipline is the only multiplier that compounds.",
  "Bankroll first, bravado later.",
  "The line gives, the line takes, the line forgets.",
  "Chase nothing but the door.",
  "A locked bet is a kept promise.",
  "Odds whisper; emotion screams.",
  "You don't beat the house. You visit it politely.",
  "Green today, ghost tomorrow.",
  "Every all-in writes its own eulogy.",
  "Patience pays in a currency you can keep.",
  "The win you keep beats the win you brag about.",
  "Down here, time is a countdown.",
  "Skulls don't bluff.",
  "Leverage is a ladder with the rungs missing.",
  "Read the spread before you read your luck.",
  "Hot hands cool fastest.",
  "The exit is undefeated.",
  "Profit is a rumor until it's withdrawn.",
  "Fear the bet you can't explain.",
  "Multipliers rise; gravity remembers.",
  "Bet sober, brag never.",
  "The board resets; your bankroll doesn't.",
  "Catch the candle, not the falling knife.",
  "Every tap is a tiny goodbye.",
  "Slow money is the only kind that stays.",
  "The flashier the cell, the colder the truth.",
  "Counting on luck is borrowing from yourself.",
  "A good stop beats a great guess.",
  "The grid rewards nerve and punishes need.",
  "One more round is the most expensive sentence ever spoken.",
  "Your edge is your exit plan.",
  "Wins are loans; the house collects.",
  "Bet the math, not the mood.",
  "The candle closes whether you watch or not.",
  "Stack discipline before you stack chips.",
  "Ruin arrives on a winning streak.",
  "Don't marry a position; date it.",
  "Small bankroll, smaller ego.",
  "The line is a heartbeat, not a promise.",
  "Cashed out and curious beats all-in and gone.",
  "Pressure turns plans into prayers.",
  "Risk what you understand, fold what you don't.",
  "Every jackpot has a witness and a warning.",
  "Walk away rich in stories, not regrets.",
  "The skull you avoid is the win you keep.",
  "Neon hides the math, not the outcome.",
  "Bet like you'll read about it tomorrow.",
  "A multiplier is a maybe wearing makeup.",
  "Hold your nerve; spend your luck slowly.",
  "Today's hero is tomorrow's cautionary tap.",
  "The grid is generous to those who leave early.",
  "Don't tap angry.",
  "Profit you can't withdraw is just a screenshot.",
  "Stop chasing; start counting.",
  "The market owes you nothing but volatility.",
  "Every winner eventually meets the cooler.",
  "Luck favors the leaving.",
  "Greed is a great entrance and a terrible exit.",
  "Bet the size you can shrug off.",
  "The countdown is honest even when you aren't.",
  "Big bets, small sleep.",
  "Survive the board, not just the bet.",
  "A 100x dream funds a 1x reality.",
  "Quit on a green and you're a legend; quit on a red and you're wise.",
  "The house edge never takes a day off.",
  "Confidence is not collateral.",
  "Tap less, keep more.",
  "Your best trade is sometimes the door.",
  "Stake what you'd lend a stranger.",
  "Variance is patient; be more patient.",
  "The line dances; don't dance with it.",
  "Win the discipline, the money follows.",
  "Cash rules; hope drools.",
  "Every skull avoided is a lesson postponed.",
  "Bet cold, count colder.",
  "The exit door is the biggest multiplier in the room.",
];

const COLORS = ["text-cyan", "text-magenta", "text-lime", "text-gold", "text-purple"];

export function randomQuote() {
  return QUOTES[Math.floor(Math.random() * QUOTES.length)];
}
export function randomColor() {
  return COLORS[Math.floor(Math.random() * COLORS.length)];
}
